# Generated by Django 4.0.6 on 2023-01-08 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=200)),
                ('cost', models.IntegerField(null=True)),
                ('time_period', models.CharField(max_length=100)),
                ('files', models.FileField(upload_to='')),
            ],
        ),
    ]
